name: CI - EASI App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test-frontend:
    name: Frontend - Lint & Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: easi-front

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test || echo "Pas de tests encore"

  lint-and-test-backend:
    name: Backend - Lint & Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: easi-back

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm run test || echo "Pas de tests encore"
